{% set name = "langchain-aws" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/langchain_aws-{{ version }}.tar.gz
  sha256: 4a6ea820d0fa720907182267040d55683ca35ea4e41c61f9afea4c13f03b1148

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.8.1,<4.0
    - langchain-core >=0.1.0,<0.2.0
    - boto3 >=1.34.51,<1.35.0
    - numpy >=1.0.0,<2.0.0

test:
  imports:
    - langchain_aws
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/langchain-ai/langchain-aws
  summary: An integration package connecting AWS and LangChain
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - 3coins
    - dlqqq
    - efriis
