{% set name = "langchain-aws" %}
{% set version = "0.1.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/langchain_aws-{{ version }}.tar.gz
  sha256: 0e8e9aa8b54f9d17fc9ddbb5576136116b88afa696cc8ed406f450c57567f3e0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.8.1,<4.0
    - langchain-core >=0.2.28,<0.3.0
    - boto3 >=1.34.131,<1.35.0
    - numpy >=1.0.0,<2.0.0

test:
  imports:
    - langchain_aws
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/langchain-ai/langchain-aws
  summary: An integration package connecting AWS and LangChain
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - 3coins
    - dlqqq
    - efriis
